---
- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/defaults.yml"

- name: Install Apache server and client on Debian and related
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - apache2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  register: apache_install
  notify:
    - apache-restart
  tags:
    - packages

- name: Install Apache server and client on RHEL derivatives
  yum: name={{ item }} state=present update-cache=yes
  with_items:
    - httpd
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'

  register: apache_install
  notify:
    - apache-restart
  tags:
    - packages

- name: Install Apache server and client on FreeBSD
  pkgng: name={{ item }} state=present
  with_items:
    - apache24
  when: ansible_distribution == 'FreeBSD'

  register: apache_install
  tags:
    - packages

- name: is Apache enable on FreeBSD
  shell: 'sysrc apache24_enable | cut -d " " -f 2'
  when: (ansible_distribution == 'FreeBSD') and apache_install

  register: isEnabled

- name: Enable Apache server
  command: 'sysrc apache24_enable=YES'
  when: (ansible_distribution == 'FreeBSD') and (isEnabled.stdout == "NO" or isEnabled.stdout == "unknown")

  notify:
    - apache-restart
