---
# tasks file for hardening

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      skip: true

# Include RedHat stuff
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

# Include FreeBSD stuff
- include_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'
