galaxy_info:
  author: Andrei Buzoianu
  description: Apply various security related best practices - server hardening
  license: WTFPL-2.0
  min_ansible_version: 2.7

  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - all
  - name: FreeBSD
    versions:
    - all

  galaxy_tags:
    - os
    - system
    - security
    - hardening

dependencies: []
