---
# Making each user have their own group with group name same as user name
users_create_same_group: true
# The group all users should belong to
users_default_group: users
# Create home dirs for new users
users_create_homedirs: true
# Lists of users and groups to create
users: ['grassharper']
groups: ['users','wheel']
